# Generated by Django 4.2.4 on 2023-08-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='startup',
        ),
    ]
